// Code generated by protoc-gen-go. DO NOT EDIT.
// source: taskModel.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskModel struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	StartAt              int64    `protobuf:"varint,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                int64    `protobuf:"varint,6,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Status               int64    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            int64    `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskModel) Reset()         { *m = TaskModel{} }
func (m *TaskModel) String() string { return proto.CompactTextString(m) }
func (*TaskModel) ProtoMessage()    {}
func (*TaskModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_84e21c40217a2c42, []int{0}
}

func (m *TaskModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskModel.Unmarshal(m, b)
}
func (m *TaskModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskModel.Marshal(b, m, deterministic)
}
func (m *TaskModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskModel.Merge(m, src)
}
func (m *TaskModel) XXX_Size() int {
	return xxx_messageInfo_TaskModel.Size(m)
}
func (m *TaskModel) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskModel.DiscardUnknown(m)
}

var xxx_messageInfo_TaskModel proto.InternalMessageInfo

func (m *TaskModel) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TaskModel) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *TaskModel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TaskModel) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *TaskModel) GetStartAt() int64 {
	if m != nil {
		return m.StartAt
	}
	return 0
}

func (m *TaskModel) GetEndAt() int64 {
	if m != nil {
		return m.EndAt
	}
	return 0
}

func (m *TaskModel) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TaskModel) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *TaskModel) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*TaskModel)(nil), "service.TaskModel")
}

func init() { proto.RegisterFile("taskModel.proto", fileDescriptor_84e21c40217a2c42) }

var fileDescriptor_84e21c40217a2c42 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xcf, 0xbf, 0x4e, 0x85, 0x30,
	0x14, 0xc7, 0xf1, 0x94, 0x3f, 0xe5, 0x72, 0x06, 0x35, 0x27, 0x6a, 0xea, 0x60, 0x42, 0x9c, 0x98,
	0xae, 0x83, 0x4f, 0x80, 0xbb, 0x0b, 0x71, 0x72, 0x31, 0xbd, 0xf4, 0x0c, 0x8d, 0x37, 0x40, 0xda,
	0x1f, 0xbe, 0xb1, 0xef, 0x61, 0x28, 0xb0, 0xf5, 0xf7, 0xfd, 0xa4, 0xc3, 0xa1, 0x5b, 0xd8, 0xf8,
	0xf3, 0x31, 0x39, 0xb9, 0x9e, 0xe7, 0x30, 0x61, 0xe2, 0x2a, 0x4a, 0xf8, 0xf5, 0x83, 0xbc, 0xfc,
	0x29, 0xaa, 0x3f, 0x0f, 0xe4, 0x1b, 0xca, 0xbc, 0x33, 0xaa, 0x51, 0x6d, 0xd1, 0x67, 0xde, 0xf1,
	0x1d, 0xe5, 0x8b, 0x77, 0x26, 0x4b, 0x61, 0x7d, 0xf2, 0x3d, 0x95, 0xf0, 0xb8, 0x8a, 0xc9, 0x1b,
	0xd5, 0xd6, 0xfd, 0x36, 0xd8, 0x50, 0x35, 0x4c, 0x23, 0x64, 0x84, 0x29, 0x52, 0x3f, 0x26, 0x3f,
	0xd1, 0x29, 0xc2, 0x06, 0x7c, 0x5b, 0x98, 0xb2, 0x51, 0x6d, 0xde, 0x57, 0x69, 0x77, 0xe0, 0x07,
	0xd2, 0x32, 0xba, 0x15, 0x74, 0x82, 0x52, 0x46, 0xd7, 0x81, 0x1f, 0x49, 0x47, 0x58, 0x2c, 0xd1,
	0x54, 0x29, 0xef, 0x8b, 0x9f, 0x89, 0x86, 0x20, 0x16, 0x92, 0xbe, 0x9c, 0x92, 0xd5, 0x7b, 0xe9,
	0xb0, 0xf2, 0x32, 0xbb, 0x83, 0xeb, 0x8d, 0xf7, 0xd2, 0xe1, 0x5d, 0x7f, 0x15, 0xe7, 0xd7, 0xf9,
	0x72, 0xd1, 0xe9, 0xfe, 0xb7, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x5e, 0x70, 0xb0, 0x12,
	0x01, 0x00, 0x00,
}
