// Code generated by protoc-gen-go. DO NOT EDIT.
// source: taskService.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	StartAt              string   `protobuf:"bytes,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                string   `protobuf:"bytes,6,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Status               int64    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            int64    `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskRequest) Reset()         { *m = TaskRequest{} }
func (m *TaskRequest) String() string { return proto.CompactTextString(m) }
func (*TaskRequest) ProtoMessage()    {}
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73398b334343aecd, []int{0}
}

func (m *TaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRequest.Unmarshal(m, b)
}
func (m *TaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRequest.Marshal(b, m, deterministic)
}
func (m *TaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRequest.Merge(m, src)
}
func (m *TaskRequest) XXX_Size() int {
	return xxx_messageInfo_TaskRequest.Size(m)
}
func (m *TaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRequest proto.InternalMessageInfo

func (m *TaskRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TaskRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *TaskRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TaskRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *TaskRequest) GetStartAt() string {
	if m != nil {
		return m.StartAt
	}
	return ""
}

func (m *TaskRequest) GetEndAt() string {
	if m != nil {
		return m.EndAt
	}
	return ""
}

func (m *TaskRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TaskRequest) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *TaskRequest) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type TaskListResponse struct {
	TaskList             []*TaskModel `protobuf:"bytes,1,rep,name=task_list,json=taskList,proto3" json:"task_list,omitempty"`
	Count                uint32       `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TaskListResponse) Reset()         { *m = TaskListResponse{} }
func (m *TaskListResponse) String() string { return proto.CompactTextString(m) }
func (*TaskListResponse) ProtoMessage()    {}
func (*TaskListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73398b334343aecd, []int{1}
}

func (m *TaskListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskListResponse.Unmarshal(m, b)
}
func (m *TaskListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskListResponse.Marshal(b, m, deterministic)
}
func (m *TaskListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskListResponse.Merge(m, src)
}
func (m *TaskListResponse) XXX_Size() int {
	return xxx_messageInfo_TaskListResponse.Size(m)
}
func (m *TaskListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskListResponse proto.InternalMessageInfo

func (m *TaskListResponse) GetTaskList() []*TaskModel {
	if m != nil {
		return m.TaskList
	}
	return nil
}

func (m *TaskListResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type TaskResponse struct {
	Task                 *TaskModel `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TaskResponse) Reset()         { *m = TaskResponse{} }
func (m *TaskResponse) String() string { return proto.CompactTextString(m) }
func (*TaskResponse) ProtoMessage()    {}
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73398b334343aecd, []int{2}
}

func (m *TaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResponse.Unmarshal(m, b)
}
func (m *TaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResponse.Marshal(b, m, deterministic)
}
func (m *TaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResponse.Merge(m, src)
}
func (m *TaskResponse) XXX_Size() int {
	return xxx_messageInfo_TaskResponse.Size(m)
}
func (m *TaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResponse proto.InternalMessageInfo

func (m *TaskResponse) GetTask() *TaskModel {
	if m != nil {
		return m.Task
	}
	return nil
}

func init() {
	proto.RegisterType((*TaskRequest)(nil), "proto.TaskRequest")
	proto.RegisterType((*TaskListResponse)(nil), "proto.TaskListResponse")
	proto.RegisterType((*TaskResponse)(nil), "proto.TaskResponse")
}

func init() { proto.RegisterFile("taskService.proto", fileDescriptor_73398b334343aecd) }

var fileDescriptor_73398b334343aecd = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4b, 0x4b, 0xfb, 0x40,
	0x14, 0xc5, 0xc9, 0xa3, 0x69, 0x73, 0xfb, 0x7f, 0xf4, 0x3f, 0x7f, 0x1f, 0x63, 0x41, 0x08, 0xc5,
	0x45, 0x36, 0x56, 0xa8, 0x76, 0xe3, 0x2e, 0x2a, 0x94, 0x82, 0x22, 0xc4, 0x8a, 0xe0, 0xa6, 0xa4,
	0xc9, 0x5d, 0x84, 0x86, 0x24, 0x66, 0x6e, 0xfc, 0x46, 0x7e, 0x36, 0xbf, 0x86, 0xcc, 0xa3, 0xd0,
	0x82, 0x2e, 0xba, 0x4a, 0xce, 0xf9, 0x71, 0xee, 0xcc, 0x3d, 0x03, 0xff, 0x28, 0x11, 0xeb, 0x27,
	0x6c, 0xde, 0xf3, 0x14, 0xc7, 0x75, 0x53, 0x51, 0xc5, 0x3a, 0xea, 0x33, 0xfc, 0x2b, 0xc9, 0x43,
	0x95, 0x61, 0xa1, 0xfd, 0xd1, 0xa7, 0x05, 0xfd, 0x45, 0x22, 0xd6, 0x31, 0xbe, 0xb5, 0x28, 0x88,
	0xfd, 0x01, 0x7b, 0x9e, 0x71, 0x2b, 0xb0, 0x42, 0x37, 0xb6, 0xe7, 0x19, 0x1b, 0x80, 0xd3, 0xe6,
	0x19, 0xb7, 0x95, 0x21, 0x7f, 0xd9, 0x01, 0x74, 0x28, 0xa7, 0x02, 0xb9, 0x13, 0x58, 0xa1, 0x1f,
	0x6b, 0xc1, 0x38, 0x74, 0xd3, 0xaa, 0x24, 0x2c, 0x89, 0xbb, 0xca, 0xdf, 0x48, 0x76, 0x02, 0x3d,
	0x41, 0x49, 0x43, 0xcb, 0x84, 0x78, 0x47, 0x23, 0xa5, 0x23, 0x62, 0x87, 0xe0, 0x61, 0x99, 0x49,
	0xe0, 0xe9, 0x59, 0x58, 0x66, 0x11, 0xb1, 0x23, 0xf0, 0x04, 0x25, 0xd4, 0x0a, 0xde, 0x0d, 0xac,
	0xd0, 0x89, 0x8d, 0x62, 0xa7, 0x00, 0x69, 0x83, 0x09, 0xa1, 0x8a, 0xf4, 0x14, 0xf3, 0x8d, 0x13,
	0x91, 0xc4, 0x6d, 0x9d, 0x6d, 0xb0, 0xaf, 0xb1, 0x71, 0x22, 0x1a, 0xbd, 0xc0, 0x40, 0x2e, 0x7a,
	0x9f, 0x0b, 0x8a, 0x51, 0xd4, 0x55, 0x29, 0x90, 0x9d, 0x83, 0x2f, 0x0b, 0x59, 0x16, 0xb9, 0x20,
	0x6e, 0x05, 0x4e, 0xd8, 0x9f, 0x0c, 0x74, 0x31, 0xe3, 0xc5, 0xa6, 0xa8, 0xb8, 0x47, 0x26, 0x26,
	0x57, 0x4f, 0xab, 0xb6, 0x24, 0x55, 0xc7, 0xef, 0x58, 0x8b, 0xd1, 0x15, 0xfc, 0xd2, 0x0d, 0x9a,
	0xa1, 0x67, 0xe0, 0xca, 0x84, 0x2a, 0xf1, 0xbb, 0x79, 0x8a, 0x4e, 0x3e, 0x6c, 0x5d, 0xbc, 0x79,
	0x26, 0x36, 0x05, 0xb8, 0x55, 0xab, 0x48, 0x93, 0xb1, 0xad, 0x94, 0x79, 0x9a, 0xe1, 0xff, 0x1d,
	0xcf, 0x1c, 0x76, 0x0d, 0xfd, 0x19, 0x92, 0xbc, 0xdd, 0x8f, 0xb9, 0xe3, 0x2d, 0x6f, 0x67, 0xfb,
	0x29, 0xc0, 0x0c, 0xe9, 0xb1, 0xdc, 0xf3, 0xc8, 0x29, 0xc0, 0xb3, 0x6a, 0x75, 0xef, 0xd8, 0x1d,
	0x16, 0xb8, 0x67, 0xec, 0xc6, 0x7b, 0x75, 0xc7, 0x17, 0xf5, 0x6a, 0xe5, 0x29, 0x76, 0xf9, 0x15,
	0x00, 0x00, 0xff, 0xff, 0x88, 0x7f, 0x5c, 0x21, 0xdc, 0x02, 0x00, 0x00,
}
